services:
  frontend:
    build:
      context: ./frontend-service
    environment:
      - HOST=http://localhost
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

  users:
    build:
      context: ./users-service
    environment:
      - HOST=http://localhost
      - PORT=3010
      - DATABASE_HOST=users-db
      - DATABASE_PORT=3011
      - DATABASE_USER=users_user
      - DATABASE_PASSWORD=users_pass
      - DATABASE_NAME=users_db
    depends_on:
      users-db:
        condition: service_healthy
    ports:
      - "3010:3010"
    networks:
      - webnet
    develop:
      watch:
        - action: rebuild
          path: .

  users-db:
    build:
      context: ./users-service-db
    environment:
      - HOST=http://localhost
      - PORT=3011
    ports:
      - "3011:3011"
    volumes:
      - ./users-service-db/data:/var/lib/postgresql/data
    networks:
      - webnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U users_user -d users_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  webnet:
