services:
  users-db:
    build:
      context: ./users-service-db
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=users_user
      - MYSQL_PASSWORD=users_pass
      - MYSQL_TCP_PORT=3011
    ports:
      - "3011:3011"
    volumes:
      - users-db-data:/var/lib/mysql
    networks:
      - webnet

  users-service:
    build:
      context: ./users-service
    container_name: users-service
    ports:
      - "3010:3010"
    depends_on:
      - users-db
    networks:
      - webnet
    environment:
      - ConnectionStrings__DefaultConnection=Server=users-db;Database=users_db;User=users_user;Password=users_pass;Port=3011;
      - ASPNETCORE_URLS=http://+:3010

  frontend:
    build:
      context: ./frontend-service
    environment:
      - HOST=http://localhost
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - webnet

networks:
  webnet:

volumes:
  users-db-data:
